# permissions for end users to edit apprunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apprunner-editor-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - apprunners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - webapp.example.com
  resources:
  - apprunners/status
  verbs:
  - get
