# permissions for end users to view apprunners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apprunner-viewer-role
rules:
- apiGroups:
  - webapp.example.com
  resources:
  - apprunners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.example.com
  resources:
  - apprunners/status
  verbs:
  - get
